#!/bin/bash
source /opt/ros/melodic/setup.bash

gnome-terminal -x bash -c "roscore;exec bash"

sleep 1
gnome-terminal -x bash -c "cd ~/iros_ws;source install/setup.bash;roslaunch base_control base_control_can_debug.launch;exec bash"

sleep 1
gnome-terminal -x bash -c "cd ~/iros_ws/base;source install/setup.bash;source ../protocomm_env;roslaunch proto_comm proto_comm_debug.launch;exec bash"

sleep 1
gnome-terminal -x bash -c "cd ~/iros_ws/driver_pkg;source install/setup.bash;roslaunch infore_robot SICK.launch;exec bash"

sleep 1
gnome-terminal -x bash -c "cd ~/iros_ws/driver_pkg;source install/setup.bash;roslaunch teleop_twist_joy joy_control_car.launch;exec bash"

