# -*- coding: utf-8 -*-
'''
本地操作指南：
    1、升级pip3:  pip3 install --upgrade pip -i https://pypi.tuna.tsinghua.edu.cn/simple
    2、安装pyqt5: pip3 install PyQt5==5.15.4 -i https://pypi.tuna.tsinghua.edu.cn/simple
    3、加入远程机器证书: ssh infore@192.168.50.221(要连接的机台，首次都需要连一下加证书)
    4、启动 roscore 后,执行: python3 tool032_ftp.py
    5、界面选择要传的本地文件,输入目标机台的文件到达路径, 点击上传。
'''
import sys
import os
import rospy
import threading
import subprocess
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow
from PyQt5.QtWidgets import QMessageBox
sign = [True, True, True, True]

class Ui_FTP(QMainWindow):
    def __init__(self):
        super(Ui_FTP, self).__init__()
        self.setupUi(self)
        self.ips = {"1CQ01": "infore@192.168.50.223", "1CQ02": "infore@192.168.50.224", "1CQ03": "infore@192.168.50.221", "1CQ04": "infore@192.168.50.222",\
                    "2KZ01": "infore@192.168.50.233", "2KZ02": "infore@192.168.50.234", "2KZ03": "infore@192.168.50.235", "2KZ04": "infore@192.168.50.236",\
                    "2CQ01": "infore@192.168.50.247", "2CQ02": "infore@192.168.50.246", "2CQ03": "infore@192.168.50.244", "2CQ04": "infore@192.168.50.245",\
                    "1ZY01": "infore@192.168.50.220", "1ZY02": "infore@192.168.50.219", "1ZY03": "infore@192.168.50.218", "1ZY04": "infore@192.168.50.217",\
                    "2ZY01": "infore@192.168.50.237", "2ZY02": "infore@192.168.50.238", "2ZY03": "infore@192.168.50.239", "2ZY04": "infore@192.168.50.240",\
                    "2ZY05": "infore@192.168.50.248", "2ZY06": "infore@192.168.50.249", "2ZY07": "infore@192.168.50.250", "2ZY08": "infore@192.168.50.251",\
                    "2ZY09": "infore@192.168.50.252", "2ZY10": "infore@192.168.50.253", "1GD01": "infore@192.168.50.229", "2GD01": "infore@192.168.50.254",\
                    "1FW01": "infore@192.168.50.216", "2FW01": "infore@192.168.50.232", "1DP01": "infore@192.168.50.225", "2DP01": "infore@192.168.50.241"
                   }
        self.toolButton_file_choice.clicked.connect(self.openFilePath)
        self.pushButton_upload.clicked.connect(self.startUploadFile)
        t_robot_choice = threading.Thread(target=self.robotChoice)
        t_robot_choice.setDaemon(True)
        t_robot_choice.start()
        self.lineEdit_file_choice_2.setText("/home/infore/iros_ws/")
        self.checkBox_1cq01.setToolTip("192.168.50.223")
        self.checkBox_1cq02.setToolTip("192.168.50.224")
        self.checkBox_1cq03.setToolTip("192.168.50.221")
        self.checkBox_1cq04.setToolTip("192.168.50.222")
        self.checkBox_2kz01.setToolTip("192.168.50.233")
        self.checkBox_2kz02.setToolTip("192.168.50.234")
        self.checkBox_2kz03.setToolTip("192.168.50.235")
        self.checkBox_2kz04.setToolTip("192.168.50.236")
        self.checkBox_2cq01.setToolTip("192.168.50.247")
        self.checkBox_2cq02.setToolTip("192.168.50.246")
        self.checkBox_2cq03.setToolTip("192.168.50.244")
        self.checkBox_2cq04.setToolTip("192.168.50.245")
        self.checkBox_1zy01.setToolTip("192.168.50.220")
        self.checkBox_1zy02.setToolTip("192.168.50.219")
        self.checkBox_1zy03.setToolTip("192.168.50.218")
        self.checkBox_1zy04.setToolTip("192.168.50.217")
        self.checkBox_2zy01.setToolTip("192.168.50.237")
        self.checkBox_2zy02.setToolTip("192.168.50.238")
        self.checkBox_2zy03.setToolTip("192.168.50.239")
        self.checkBox_2zy04.setToolTip("192.168.50.240")
        self.checkBox_2zy05.setToolTip("192.168.50.248")
        self.checkBox_2zy06.setToolTip("192.168.50.249")
        self.checkBox_2zy07.setToolTip("192.168.50.250")
        self.checkBox_2zy08.setToolTip("192.168.50.251")
        self.checkBox_2zy09.setToolTip("192.168.50.252")
        self.checkBox_2zy10.setToolTip("192.168.50.253")
        self.checkBox_1gd01.setToolTip("192.168.50.229")
        self.checkBox_2gd01.setToolTip("192.168.50.254")
        self.checkBox_1fw01.setToolTip("192.168.50.216")
        self.checkBox_2fw01.setToolTip("192.168.50.232")
        self.checkBox_1dp01.setToolTip("192.168.50.225")
        self.checkBox_2dp01.setToolTip("192.168.50.241")

    def setupUi(self, FTP):
        FTP.setObjectName("FTP")
        FTP.resize(1061, 667)
        self.centralWidget = QtWidgets.QWidget(FTP)
        self.centralWidget.setObjectName("centralWidget")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(440, 0, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: red")
        self.label.setObjectName("label")
        self.checkBox_all = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox_all.setGeometry(QtCore.QRect(10, 110, 71, 23))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_all.setFont(font)
        self.checkBox_all.setObjectName("checkBox_all")
        self.checkBox_1cq01 = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox_1cq01.setGeometry(QtCore.QRect(30, 170, 81, 23))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_1cq01.setFont(font)
        self.checkBox_1cq01.setStyleSheet("")
        self.checkBox_1cq01.setObjectName("checkBox_1cq01")
        self.checkBox_1cq02 = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox_1cq02.setGeometry(QtCore.QRect(130, 170, 81, 23))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_1cq02.setFont(font)
        self.checkBox_1cq02.setStyleSheet("")
        self.checkBox_1cq02.setObjectName("checkBox_1cq02")
        self.checkBox_1cq03 = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox_1cq03.setGeometry(QtCore.QRect(230, 170, 81, 23))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_1cq03.setFont(font)
        self.checkBox_1cq03.setStyleSheet("")
        self.checkBox_1cq03.setObjectName("checkBox_1cq03")
        self.checkBox_1cq04 = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox_1cq04.setGeometry(QtCore.QRect(330, 170, 81, 23))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_1cq04.setFont(font)
        self.checkBox_1cq04.setStyleSheet("")
        self.checkBox_1cq04.setObjectName("checkBox_1cq04")
        self.checkBox_1dp01 = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox_1dp01.setGeometry(QtCore.QRect(30, 510, 71, 23))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_1dp01.setFont(font)
        self.checkBox_1dp01.setStyleSheet("")
        self.checkBox_1dp01.setObjectName("checkBox_1dp01")
        self.checkBox_1gd01 = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox_1gd01.setGeometry(QtCore.QRect(30, 370, 81, 23))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_1gd01.setFont(font)
        self.checkBox_1gd01.setStyleSheet("")
        self.checkBox_1gd01.setObjectName("checkBox_1gd01")
        self.checkBox_2dp01 = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox_2dp01.setGeometry(QtCore.QRect(130, 510, 81, 23))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_2dp01.setFont(font)
        self.checkBox_2dp01.setStyleSheet("")
        self.checkBox_2dp01.setObjectName("checkBox_2dp01")
        self.checkBox_1zy01 = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox_1zy01.setGeometry(QtCore.QRect(30, 270, 81, 23))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_1zy01.setFont(font)
        self.checkBox_1zy01.setStyleSheet("")
        self.checkBox_1zy01.setObjectName("checkBox_1zy01")
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(110, 45, 81, 17))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.toolButton_file_choice = QtWidgets.QToolButton(self.centralWidget)
        self.toolButton_file_choice.setGeometry(QtCore.QRect(780, 40, 26, 31))
        self.toolButton_file_choice.setObjectName("toolButton_file_choice")
        self.lineEdit_file_choice = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_file_choice.setGeometry(QtCore.QRect(190, 40, 591, 31))
        self.lineEdit_file_choice.setObjectName("lineEdit_file_choice")
        self.pushButton_upload = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_upload.setGeometry(QtCore.QRect(818, 40, 121, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_upload.setFont(font)
        self.pushButton_upload.setObjectName("pushButton_upload")
        self.label_3 = QtWidgets.QLabel(self.centralWidget)
        self.label_3.setGeometry(QtCore.QRect(110, 85, 81, 17))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit_file_choice_2 = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_file_choice_2.setGeometry(QtCore.QRect(190, 80, 591, 31))
        self.lineEdit_file_choice_2.setObjectName("lineEdit_file_choice_2")
        self.checkBox_2kz01 = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox_2kz01.setGeometry(QtCore.QRect(430, 170, 81, 23))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_2kz01.setFont(font)
        self.checkBox_2kz01.setStyleSheet("")
        self.checkBox_2kz01.setObjectName("checkBox_2kz01")
        self.checkBox_2kz02 = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox_2kz02.setGeometry(QtCore.QRect(530, 170, 81, 23))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_2kz02.setFont(font)
        self.checkBox_2kz02.setStyleSheet("")
        self.checkBox_2kz02.setObjectName("checkBox_2kz02")
        self.checkBox_2kz03 = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox_2kz03.setGeometry(QtCore.QRect(630, 170, 81, 23))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_2kz03.setFont(font)
        self.checkBox_2kz03.setStyleSheet("")
        self.checkBox_2kz03.setObjectName("checkBox_2kz03")
        self.checkBox_2kz04 = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox_2kz04.setGeometry(QtCore.QRect(730, 170, 81, 23))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_2kz04.setFont(font)
        self.checkBox_2kz04.setStyleSheet("")
        self.checkBox_2kz04.setObjectName("checkBox_2kz04")
        self.checkBox_2cq01 = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox_2cq01.setGeometry(QtCore.QRect(830, 170, 81, 23))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_2cq01.setFont(font)
        self.checkBox_2cq01.setStyleSheet("")
        self.checkBox_2cq01.setObjectName("checkBox_2cq01")
        self.checkBox_2cq02 = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox_2cq02.setGeometry(QtCore.QRect(930, 170, 81, 23))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_2cq02.setFont(font)
        self.checkBox_2cq02.setStyleSheet("")
        self.checkBox_2cq02.setObjectName("checkBox_2cq02")
        self.checkBox_2cq03 = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox_2cq03.setGeometry(QtCore.QRect(30, 200, 81, 23))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_2cq03.setFont(font)
        self.checkBox_2cq03.setStyleSheet("")
        self.checkBox_2cq03.setObjectName("checkBox_2cq03")
        self.checkBox_2cq04 = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox_2cq04.setGeometry(QtCore.QRect(130, 200, 81, 23))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_2cq04.setFont(font)
        self.checkBox_2cq04.setStyleSheet("")
        self.checkBox_2cq04.setObjectName("checkBox_2cq04")
        self.checkBox_1zy02 = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox_1zy02.setGeometry(QtCore.QRect(130, 270, 81, 23))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_1zy02.setFont(font)
        self.checkBox_1zy02.setStyleSheet("")
        self.checkBox_1zy02.setObjectName("checkBox_1zy02")
        self.checkBox_1zy03 = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox_1zy03.setGeometry(QtCore.QRect(230, 270, 81, 23))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_1zy03.setFont(font)
        self.checkBox_1zy03.setStyleSheet("")
        self.checkBox_1zy03.setObjectName("checkBox_1zy03")
        self.checkBox_1zy04 = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox_1zy04.setGeometry(QtCore.QRect(330, 270, 81, 23))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_1zy04.setFont(font)
        self.checkBox_1zy04.setStyleSheet("")
        self.checkBox_1zy04.setObjectName("checkBox_1zy04")
        self.checkBox_2zy01 = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox_2zy01.setGeometry(QtCore.QRect(430, 270, 81, 23))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_2zy01.setFont(font)
        self.checkBox_2zy01.setStyleSheet("")
        self.checkBox_2zy01.setObjectName("checkBox_2zy01")
        self.checkBox_2zy02 = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox_2zy02.setGeometry(QtCore.QRect(530, 270, 81, 23))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_2zy02.setFont(font)
        self.checkBox_2zy02.setStyleSheet("")
        self.checkBox_2zy02.setObjectName("checkBox_2zy02")
        self.checkBox_2zy03 = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox_2zy03.setGeometry(QtCore.QRect(630, 270, 81, 23))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_2zy03.setFont(font)
        self.checkBox_2zy03.setStyleSheet("")
        self.checkBox_2zy03.setObjectName("checkBox_2zy03")
        self.checkBox_2zy04 = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox_2zy04.setGeometry(QtCore.QRect(730, 270, 81, 23))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_2zy04.setFont(font)
        self.checkBox_2zy04.setStyleSheet("")
        self.checkBox_2zy04.setObjectName("checkBox_2zy04")
        self.checkBox_2zy05 = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox_2zy05.setGeometry(QtCore.QRect(830, 270, 81, 23))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_2zy05.setFont(font)
        self.checkBox_2zy05.setStyleSheet("")
        self.checkBox_2zy05.setObjectName("checkBox_2zy05")
        self.checkBox_2zy06 = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox_2zy06.setGeometry(QtCore.QRect(930, 270, 81, 23))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_2zy06.setFont(font)
        self.checkBox_2zy06.setStyleSheet("")
        self.checkBox_2zy06.setObjectName("checkBox_2zy06")
        self.checkBox_2zy07 = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox_2zy07.setGeometry(QtCore.QRect(30, 300, 81, 23))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_2zy07.setFont(font)
        self.checkBox_2zy07.setStyleSheet("")
        self.checkBox_2zy07.setObjectName("checkBox_2zy07")
        self.checkBox_2zy08 = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox_2zy08.setGeometry(QtCore.QRect(130, 300, 81, 23))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_2zy08.setFont(font)
        self.checkBox_2zy08.setStyleSheet("")
        self.checkBox_2zy08.setObjectName("checkBox_2zy08")
        self.checkBox_2zy09 = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox_2zy09.setGeometry(QtCore.QRect(230, 300, 81, 23))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_2zy09.setFont(font)
        self.checkBox_2zy09.setStyleSheet("")
        self.checkBox_2zy09.setObjectName("checkBox_2zy09")
        self.checkBox_2zy10 = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox_2zy10.setGeometry(QtCore.QRect(330, 300, 81, 23))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_2zy10.setFont(font)
        self.checkBox_2zy10.setStyleSheet("")
        self.checkBox_2zy10.setObjectName("checkBox_2zy10")
        self.checkBox_1fw01 = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox_1fw01.setGeometry(QtCore.QRect(30, 440, 81, 23))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_1fw01.setFont(font)
        self.checkBox_1fw01.setStyleSheet("")
        self.checkBox_1fw01.setObjectName("checkBox_1fw01")
        self.checkBox_2fw01 = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox_2fw01.setGeometry(QtCore.QRect(130, 440, 81, 23))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_2fw01.setFont(font)
        self.checkBox_2fw01.setStyleSheet("")
        self.checkBox_2fw01.setObjectName("checkBox_2fw01")
        self.checkBox_2gd01 = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox_2gd01.setGeometry(QtCore.QRect(130, 370, 81, 23))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_2gd01.setFont(font)
        self.checkBox_2gd01.setStyleSheet("")
        self.checkBox_2gd01.setObjectName("checkBox_2gd01")
        self.line = QtWidgets.QFrame(self.centralWidget)
        self.line.setGeometry(QtCore.QRect(10, 230, 1041, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralWidget)
        self.line_2.setGeometry(QtCore.QRect(10, 330, 1041, 20))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.line_2.setFont(font)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralWidget)
        self.line_3.setGeometry(QtCore.QRect(10, 400, 1041, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralWidget)
        self.line_4.setGeometry(QtCore.QRect(10, 470, 1041, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.checkBox_qm_all = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox_qm_all.setGeometry(QtCore.QRect(10, 140, 71, 23))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_qm_all.setFont(font)
        self.checkBox_qm_all.setStyleSheet("color: rgb(239, 41, 41);")
        self.checkBox_qm_all.setObjectName("checkBox_qm_all")
        self.checkBox_zhuoyi_all = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox_zhuoyi_all.setGeometry(QtCore.QRect(10, 240, 71, 23))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_zhuoyi_all.setFont(font)
        self.checkBox_zhuoyi_all.setStyleSheet("color: rgb(239, 41, 41);")
        self.checkBox_zhuoyi_all.setObjectName("checkBox_zhuoyi_all")
        self.checkBox_gd_all = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox_gd_all.setGeometry(QtCore.QRect(10, 340, 71, 23))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_gd_all.setFont(font)
        self.checkBox_gd_all.setStyleSheet("color: rgb(239, 41, 41);")
        self.checkBox_gd_all.setObjectName("checkBox_gd_all")
        self.checkBox_dingp_all = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox_dingp_all.setGeometry(QtCore.QRect(10, 480, 71, 23))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_dingp_all.setFont(font)
        self.checkBox_dingp_all.setStyleSheet("color: rgb(239, 41, 41);")
        self.checkBox_dingp_all.setObjectName("checkBox_dingp_all")
        self.checkBox_fwt_all = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox_fwt_all.setGeometry(QtCore.QRect(10, 410, 91, 23))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_fwt_all.setFont(font)
        self.checkBox_fwt_all.setStyleSheet("color: rgb(239, 41, 41);")
        self.checkBox_fwt_all.setObjectName("checkBox_fwt_all")
        FTP.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(FTP)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1061, 28))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menuBar)
        self.menu_2.setObjectName("menu_2")
        FTP.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(FTP)
        self.statusBar.setObjectName("statusBar")
        FTP.setStatusBar(self.statusBar)
        self.menuBar.addAction(self.menu.menuAction())
        self.menuBar.addAction(self.menu_2.menuAction())

        self.retranslateUi(FTP)
        QtCore.QMetaObject.connectSlotsByName(FTP)

    def retranslateUi(self, FTP):
        _translate = QtCore.QCoreApplication.translate
        FTP.setWindowTitle(_translate("FTP", "FTP"))
        self.label.setText(_translate("FTP", "文件远程传输工具"))
        self.checkBox_all.setText(_translate("FTP", "全选"))
        self.checkBox_1cq01.setText(_translate("FTP", "1CQ01"))
        self.checkBox_1cq02.setText(_translate("FTP", "1CQ02"))
        self.checkBox_1cq03.setText(_translate("FTP", "1CQ03"))
        self.checkBox_1cq04.setText(_translate("FTP", "1CQ04"))
        self.checkBox_1dp01.setText(_translate("FTP", "1DP01"))
        self.checkBox_1gd01.setText(_translate("FTP", "1GD01"))
        self.checkBox_2dp01.setText(_translate("FTP", "2DP01"))
        self.checkBox_1zy01.setText(_translate("FTP", "1ZY01"))
        self.label_2.setText(_translate("FTP", "上传文件："))
        self.toolButton_file_choice.setText(_translate("FTP", "..."))
        self.pushButton_upload.setText(_translate("FTP", "开始\n"
"上传"))
        self.label_3.setText(_translate("FTP", "目标路径："))
        self.checkBox_2kz01.setText(_translate("FTP", "2KZ01"))
        self.checkBox_2kz02.setText(_translate("FTP", "2KZ02"))
        self.checkBox_2kz03.setText(_translate("FTP", "2KZ03"))
        self.checkBox_2kz04.setText(_translate("FTP", "2KZ04"))
        self.checkBox_2cq01.setText(_translate("FTP", "2CQ01"))
        self.checkBox_2cq02.setText(_translate("FTP", "2CQ02"))
        self.checkBox_2cq03.setText(_translate("FTP", "2CQ03"))
        self.checkBox_2cq04.setText(_translate("FTP", "2CQ04"))
        self.checkBox_1zy02.setText(_translate("FTP", "1ZY02"))
        self.checkBox_1zy03.setText(_translate("FTP", "1ZY03"))
        self.checkBox_1zy04.setText(_translate("FTP", "1ZY04"))
        self.checkBox_2zy01.setText(_translate("FTP", "2ZY01"))
        self.checkBox_2zy02.setText(_translate("FTP", "2ZY02"))
        self.checkBox_2zy03.setText(_translate("FTP", "2ZY03"))
        self.checkBox_2zy04.setText(_translate("FTP", "2ZY04"))
        self.checkBox_2zy05.setText(_translate("FTP", "2ZY05"))
        self.checkBox_2zy06.setText(_translate("FTP", "2ZY06"))
        self.checkBox_2zy07.setText(_translate("FTP", "2ZY07"))
        self.checkBox_2zy08.setText(_translate("FTP", "2ZY08"))
        self.checkBox_2zy09.setText(_translate("FTP", "2ZY09"))
        self.checkBox_2zy10.setText(_translate("FTP", "2ZY10"))
        self.checkBox_1fw01.setText(_translate("FTP", "1FW01"))
        self.checkBox_2fw01.setText(_translate("FTP", "2FW01"))
        self.checkBox_2gd01.setText(_translate("FTP", "2GD01"))
        self.checkBox_qm_all.setText(_translate("FTP", "墙面："))
        self.checkBox_zhuoyi_all.setText(_translate("FTP", "桌椅："))
        self.checkBox_gd_all.setText(_translate("FTP", "供电："))
        self.checkBox_dingp_all.setText(_translate("FTP", "顶棚："))
        self.checkBox_fwt_all.setText(_translate("FTP", "服务台："))
        self.menu.setTitle(_translate("FTP", "文件"))
        self.menu_2.setTitle(_translate("FTP", "关于"))

    def robotChoice(self):
        
        global sign
        rate = rospy.Rate(2)
        while not rospy.is_shutdown():
            self.robot_name =  [self.checkBox_1cq01, self.checkBox_1cq02, self.checkBox_1cq03, self.checkBox_1cq04,\
                                self.checkBox_2kz01, self.checkBox_2kz02, self.checkBox_2kz03, self.checkBox_2kz04,\
                                self.checkBox_2cq01, self.checkBox_2cq02, self.checkBox_2cq03, self.checkBox_2cq04,\
                                self.checkBox_1zy01, self.checkBox_1zy02, self.checkBox_1zy03, self.checkBox_1zy04,\
                                self.checkBox_2zy01, self.checkBox_2zy02, self.checkBox_2zy03, self.checkBox_2zy04,\
                                self.checkBox_2zy05, self.checkBox_2zy06, self.checkBox_2zy07, self.checkBox_2zy08,\
                                self.checkBox_2zy09, self.checkBox_2zy10, self.checkBox_1gd01, self.checkBox_2gd01,\
                                self.checkBox_1fw01, self.checkBox_2fw01, self.checkBox_1dp01, self.checkBox_2dp01
                               ]
            robot_name_checked = []
            for i in self.robot_name:
                robot_name_checked.append(i.isChecked())

            if self.checkBox_all.isChecked() == True and (sign[0] or sign[3]):
                for robot in self.robot_name:
                    robot.setChecked(True)
                sign = [False, True, False, False]
            elif self.checkBox_all.isChecked() == False and (sign[1] or sign[2]):
                for robot in self.robot_name:
                    robot.setChecked(False)
                sign = [True, False, False, False]
            elif not all(robot_name_checked) and (sign[1] or sign[2]):
                self.checkBox_all.setChecked(False)
                sign = [False, False, False, True]

            elif all(robot_name_checked) and (sign[0] or sign[3]):
                self.checkBox_all.setChecked(True)
                sign = [False, False, True, False]
            rate.sleep()

    def openFilePath(self):
        # file_path = QtWidgets.QFileDialog.getOpenFileName(None,"选取文件夹","/home")
        # self.lineEdit_file_choice.setText(file_path)  # 设置文本内容
        file_name,ok = QtWidgets.QFileDialog.getOpenFileName(self,"选取单个文件",os.getcwd()) # 选择单个文件
        # get_filenames, ok =QtWidgets.QFileDialog.getOpenFileNames(self,"选取多个文件","/home","All Files (*);;Text Files (*.txt)")
        # self.filePathlineEdit.setText(str(' '.join(get_filenames)))
        # file_path = QtWidgets.QFileDialog.getExistingDirectory(None,"选取文件夹","/home")  # 选择文件夹
        self.lineEdit_file_choice.clear()
        self.lineEdit_file_choice.setText(str(file_name))  # 设置文本内容

    def startUploadFile1(self):
        global ip
        ip_choice = []
        infomation_ok = ""
        infomation_ng = ""
        for robot in self.robot_name:
            if robot.isChecked():
                robot_no = robot.text()
                for robot_key ,value in self.ips.items():
                    if robot_no == robot_key:
                        ip_choice.append(value)
        # print(f"ips:{ip_choice}")
        for ip in ip_choice:
            if self.lineEdit_file_choice.text() == "":
                QMessageBox.warning(None, "警告", "路径为空，请正确选择！", QMessageBox.Ok)
                return
            cmd = "sshpass -p 123 scp -r " + self.lineEdit_file_choice.text() + " " + ip + ":" + self.lineEdit_file_choice_2.text()
            print(cmd)
            message = os.popen(cmd).read().rstrip()
            print(f"message = {message}")
            if(message != ""):
                infomation_ng = ip + "\n" + infomation_ng
                rospy.logerr(f"{ip}拷贝失败！")
            if(message == ""):
                infomation_ok = ip + "\n" + infomation_ok
                print(f"{ip}拷贝完成！")  
        QMessageBox.information(None, "提示", f"拷贝完成:\n{infomation_ok}\n---\n拷贝失败:\n{infomation_ng}")

    def startUploadFile(self):
        global ip
        ip_choice = []
        infomation_ok = ""
        infomation_ng = ""
        for robot in self.robot_name:
            if robot.isChecked():
                robot_no = robot.text()
                for robot_key ,value in self.ips.items():
                    if robot_no == robot_key:
                        ip_choice.append(value)
        # print(f"ips:{ip_choice}")
        for ip in ip_choice:
            if self.lineEdit_file_choice.text() == "":
                QMessageBox.warning(None, "警告", "路径为空，请正确选择！", QMessageBox.Ok)
                return
            cmd = "sshpass -p 123 scp -r " + self.lineEdit_file_choice.text() + " " + ip + ":" + self.lineEdit_file_choice_2.text()
            # print(cmd)
            message = subprocess.run(cmd, shell=True)            
            if(message.returncode == 0):
                for key1,value1 in self.ips.items():
                    if value1 == ip:
                        infomation_ok = key1 + "\n" + infomation_ok
                        print(f"{key1}拷贝完成！")  
            else:
                for key2,value2 in self.ips.items():
                    if value2 == ip:
                        infomation_ng = key2 + "\n" + infomation_ng
                        rospy.logerr(f"{key2}拷贝失败！")
        QMessageBox.information(None, "提示", f"拷贝完成:\n{infomation_ok}\n---\n拷贝失败:\n{infomation_ng}")
        rospy.logerr(f"所有失败机台为：\n{infomation_ng}")



if __name__ == "__main__":
    rospy.init_node("upload_file_node")
    app = QtWidgets.QApplication(sys.argv)
    ftp1 = Ui_FTP()
    ftp1.show()
    sys.exit(app.exec_())